### ISSUE TITLE
BOT looks like not effective

### ISSUE THREAD

**Issue by FanaticPond3462** [SC-dev-team/CalicoBot#11]
[2023-09-18 01:11:48] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'channelselect'
Sep 18 10:11:48 AM  Traceback (most recent call last):
Sep 18 10:11:48 AM    File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
Sep 18 10:11:48 AM      return await self._callback(self.binding, interaction, **params)  # type: ignore
Sep 18 10:11:48 AM             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 18 10:11:48 AM    File "/opt/render/project/src/command.py", line 251, in channelselect
Sep 18 10:11:48 AM      bot_icon=await BOT.user.avatar.read()
Sep 18 10:11:48 AM                     ^^^^^^^^
Sep 18 10:11:48 AM  AttributeError: 'NoneType' object has no attribute 'user'
Sep 18 10:11:48 AM
Sep 18 10:11:48 AM  The above exception was the direct cause of the following exception:
Sep 18 10:11:48 AM
Sep 18 10:11:48 AM  Traceback (most recent call last):
Sep 18 10:11:48 AM    File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
Sep 18 10:11:48 AM      await command._invoke_with_namespace(interaction, namespace)
Sep 18 10:11:48 AM    File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
Sep 18 10:11:48 AM      return await self._do_call(interaction, transformed_values)
Sep 18 10:11:48 AM             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 18 10:11:48 AM    File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
Sep 18 10:11:48 AM      raise CommandInvokeError(self, e) from e
Sep 18 10:11:48 AM  discord.app_commands.errors.CommandInvokeError: Command 'channelselect' raised an exception: AttributeError: 'NoneType' object has no attribute 'user'

**Comment by FanaticPond3462** [comment]
This problem was solved at #12
